## Assignment Solution 

- Write a function so that the columns of the output matrix are powers of the input vector.
- The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.

- HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.


In [1]:
import numpy as np

In [3]:
def output_mat():
    x = np.array([1,2,3,4,5,6,7,8,9,10])
    N=5
    matrix = np.column_stack([x**(N-i-1) for i in range(N)])
    print(matrix)

In [5]:
print(f"The Output matrix according to the logic is: ")
output_mat()

The Output matrix according to the logic is: 
[[    1     1     1     1     1]
 [   16     8     4     2     1]
 [   81    27     9     3     1]
 [  256    64    16     4     1]
 [  625   125    25     5     1]
 [ 1296   216    36     6     1]
 [ 2401   343    49     7     1]
 [ 4096   512    64     8     1]
 [ 6561   729    81     9     1]
 [10000  1000   100    10     1]]


### Directly making use of Vander method available in Numpy 

In [13]:
def vander_matrix():
    x_1 = np.array([1,2,3,4,5,6,7,8,9,10])
    N = 5
    matrix_1 = np.vander(x_1,N,increasing=False)
    print(matrix_1)

In [14]:
vander_matrix()

[[    1     1     1     1     1]
 [   16     8     4     2     1]
 [   81    27     9     3     1]
 [  256    64    16     4     1]
 [  625   125    25     5     1]
 [ 1296   216    36     6     1]
 [ 2401   343    49     7     1]
 [ 4096   512    64     8     1]
 [ 6561   729    81     9     1]
 [10000  1000   100    10     1]]


### Question: Write a function to find moving average in an array over a window: 
- Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3

In [17]:
def moving_average(list, N):
    cumsum, moving_aves = [0], []
    for i, x in enumerate(list, 1):
        cumsum.append(cumsum[i-1] + x) # summing up all the values one by one and appending the list
        if i>=N:
            moving_ave = round(((cumsum[i] - cumsum[i-N])/N),2) #computing the moving average using temp array sum array cumsum
            #can do stuff with moving_ave here
            moving_aves.append(moving_ave) # listing the moving average as an single array
    print("Moving average values list: ", moving_aves)
    print("Length of the list l-N+1: ", len(moving_aves))

In [18]:
list = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N = 5
moving_average(list,N)

Moving average values list:  [5.0, 6.4, 7.6, 19.2, 33.2, 47.8, 65.6, 83.4, 100.4]
Length of the list l-N+1:  9
